export type Locale = "de" | "en";
export type SectorId = "web" | "games" | "labs";
export const sectorOrder: SectorId[] = ["web", "games", "labs"];
export const copy = {
  de: {
    meta: { title: "emfau — Web, Games & Labs", description: "emfau entwickelt Websites, Browsergames, Prototypen und technische Tools." },
    navLabel: "Navigation", menuOpen: "Menü öffnen", menuClose: "Menü schließen", language: "Sprache",
    navigation: { web: "Web", games: "Games", labs: "Labs", about: "Über emfau", contact: "Kontakt" },
    hero: { kicker: "Webentwicklung · Games · Tools", titleStart: "Websites,", titleAccent: "Spiele", titleEnd: "und digitale Werkzeuge.", intro: "emfau entwickelt Websites, Browsergames, Prototypen und technische Tools – von der ersten Idee bis zur funktionierenden Umsetzung.", prompt: "Bereich auswählen", note: "Bereich auswählen" },
    sectors: {
      web: { number: "01", title: "Web", eyebrow: "Websites & Webentwicklung", lead: "Websites für Vereine, kleine Unternehmen und Selbstständige – übersichtlich, responsive und auf den jeweiligen Bedarf zugeschnitten.", body: "Von Struktur und Gestaltung bis zur technischen Umsetzung. Bestehende Websites können überarbeitet, erweitert oder vollständig neu aufgebaut werden.", services: [["Webdesign", "Individuelle Gestaltung mit klarer Struktur und guter Bedienbarkeit."], ["Entwicklung", "Responsive Websites mit einer soliden technischen Grundlage."], ["Überarbeitung", "Bestehende Seiten modernisieren, neu strukturieren oder erweitern."]], cta: "Web-Projekte ansehen" },
      games: { number: "02", title: "Games", eyebrow: "Browsergames & Prototypen", lead: "Eigene Browsergames und spielbare Prototypen mit unterschiedlichen Mechaniken und Genres.", body: "Die Projekte entstehen schrittweise: Konzept, spielbarer Stand, Tests, Feedback und Weiterentwicklung bis zur Veröffentlichung.", services: [["Game Design", "Spielideen und Mechaniken entwickeln und praktisch testen."], ["Prototyping", "Ideen früh in einen spielbaren Stand bringen."], ["Browsergames", "Spiele für moderne Browser und unterschiedliche Plattformen entwickeln."]], cta: "Games ansehen" },
      labs: { number: "03", title: "Labs", eyebrow: "Tools, Frameworks & Experimente", lead: "Technische Werkzeuge und wiederverwendbare Bausteine, die aus eigenen Projekten und konkreten Anforderungen entstehen.", body: "Dazu gehören kleine Anwendungen, Frameworks und Versuche mit Webtechnologien, 3D, interaktiven Anwendungen und neuen Entwicklungsansätzen.", services: [["Tools", "Kleine Anwendungen für konkrete Aufgaben und Abläufe."], ["Frameworks", "Wiederverwendbare Grundlagen für weitere Projekte."], ["Experimente", "Neue Technologien und technische Ansätze praktisch erproben."]], cta: "Labs ansehen" },
    },
    about: { kicker: "Über emfau", title: "Webentwicklung, Games und technische Projekte.", body: "emfau bündelt meine Arbeit an Websites, Browsergames und eigenen Tools. Die Projekte reichen von Webkonzepten für Vereine und kleinere Unternehmen über veröffentlichte Spiele bis zu Prototypen und wiederverwendbaren technischen Bausteinen.", facts: [["01", "Direkte Abstimmung"], ["02", "Gestaltung & Entwicklung"], ["03", "Prototypen & reale Projekte"]] },
    contact: { kicker: "KONTAKT", title: "Ein Projekt oder eine Frage?", body: "Kurz beschreiben, worum es geht. Ich schaue mir das Vorhaben an und gebe eine Einschätzung zur möglichen Umsetzung.", cta: "Kontakt aufnehmen", note: "Kontakt aufnehmen" },
    footer: { top: "Nach oben", legal: "Rechtliche Angaben folgen vor Veröffentlichung.", tagline: "Web • Games • Labs • emfau" },
    gateway: { kicker: "Bereichsvorschau", back: "Zurück zum emfau Hub", titleSuffix: "wird gerade vorbereitet.", body: "Die Zielseite ist bereits sauber angebunden. Inhalte und externe Ziele werden in einem späteren Bulk ergänzt.", cta: "Interesse vormerken" },
  },
  en: {
    meta: { title: "emfau — Web, Games & Labs", description: "emfau creates clear websites, playable ideas and useful technical tools." },
    navLabel: "Navigation", menuOpen: "Open menu", menuClose: "Close menu", language: "Language",
    navigation: { web: "Web", games: "Games", labs: "Labs", about: "About emfau", contact: "Contact" },
    hero: { kicker: "Independent digital studio", titleStart: "Digital experiences,", titleAccent: "games", titleEnd: "and tools.", intro: "emfau brings clear websites, playable ideas and technical experiments together under one roof.", prompt: "Where do you want to go?", note: "Choose a direction" },
    sectors: {
      web: { number: "01", title: "Web", eyebrow: "Websites & presence", lead: "Digital experiences people understand quickly — for clubs, small businesses and independent professionals.", body: "From a clear structure to the technical build, every site is made to fit, stay easy to use and grow with its purpose.", services: [["Web design", "Distinctive design with a clear visual language."], ["Development", "Fast, responsive websites with a solid technical base."], ["Evolution", "Restructure, modernise and extend existing websites."]], cta: "Explore Web" },
      games: { number: "02", title: "Games", eyebrow: "Games & prototypes", lead: "Small worlds, focused mechanics and ideas that truly come alive through play.", body: "emfau Games is a space for original projects, playable prototypes and experiments between design, code and interaction.", services: [["Game concepts", "Make mechanics and game ideas tangible early on."], ["Prototyping", "From the first loop to a convincing playable build."], ["Interactive", "Playful formats for the web, events and special stories."]], cta: "View Games" },
      labs: { number: "03", title: "Labs", eyebrow: "Frameworks & tools", lead: "Technical building blocks and open experiments for problems that call for a purpose-built solution.", body: "Labs is where tools, frameworks and reusable systems take shape — practical, understandable and driven by curiosity.", services: [["Tools", "Small helpers that simplify workflows and give time back."], ["Frameworks", "Reusable foundations for consistent digital products."], ["Experiments", "Test technologies before an idea becomes a product."]], cta: "Open Labs" },
    },
    about: { kicker: "One studio, three directions", title: "Good digital work starts with curiosity and ends with clarity.", body: "emfau brings design and development together. Websites, games and tools do not emerge in isolation, but from the same attitude: clear, distinctive and attentive to detail.", facts: [["01", "Direct collaboration"], ["02", "Design + code"], ["03", "From idea to release"]] },
    contact: { kicker: "Have a project in mind?", title: "Let’s find out what it could become.", body: "Share the outline of your idea. The public contact address will be added before release; until then, this area is clearly marked as a preview.", cta: "Contact coming soon", note: "Add contact address before publication" },
    footer: { top: "Back to top", legal: "Legal details will be added before publication.", tagline: "Web • Games • Labs • emfau" },
    gateway: { kicker: "Section preview", back: "Back to the emfau hub", titleSuffix: "is being prepared.", body: "The destination page is already connected. Content and external destinations will be added in a later bulk.", cta: "Register interest" },
  },
} as const;